import tkinter
from tkinter import *
from PIL import Image, ImageTk
import mysql.connector as sq
cn = sq.connect(host="localhost", user="root", passwd="root",database='spd')
cur=cn.cursor()

window = Tk() # Create a window
window.title('bank Management system ')
window.geometry("1500x1500")
def window1():
    frame1 = Frame(bd=0, highlightthickness=0, background="white")
    frame2 =Frame(bd=0, highlightthickness=0, background="orange")
    frame1.place(x=0, y=0, relwidth=1.0, relheight=.3, anchor="nw")
    frame2.place(x=0, rely=.3, relwidth=1.0, relheight=.7, anchor="nw")
    l1=Label(window,text="               Bank Management System            ",bg='white',fg='black',font=("MS Sans Serif",58))
    l1.place(x=40,y=100)
    def createaccountdb(e1,e2,e3,e4,e5,e6,e7,e8):
        e1=e1.get()
        e2=e2.get()
        e3=e3.get()
        e4=e4.get()
        e5=e5.get()
        e6=e6.get()
        e7=e7.get()
        e8=e8.get()

        if e1!='' and e2!='' and e3!='' and e4!='' and e5!='' and e6!='' and e7!=0 and e8!='':
            if int(e7)==1:
                gen='M'
            if int(e7)==2:
                gen='F'
            cur.execute("CREATE TABLE IF NOT EXISTS account(account_no Int(20) primary key,first varchar(10),last varchar(10),amount float,address varchar(40),phone Int(11),gender char(2),email varchar(30))")
            qry="INSERT INTO account values('{}','{}','{}','{}','{}','{}','{}','{}')".format(e1,e2,e3,e4,e5,e6,gen,e8)
            cur.execute(qry)
            cn.commit()
            new1=Label(window,text='Account Created          \n Successfully',bg='orange',fg='indianred2',font=("Berlin sans FB",18))
            new1.place(x=1100,y=500)
        else:
            new1=Label(window,text='Please fill      \n all the fields',bg='orange',fg='indianred2',font=("Berlin sans FB",18))
            new1.place(x=1100,y=500)
        
    def createaccount():
        frame1 = Frame(bd=0, highlightthickness=0, background="white")
        frame2 =Frame(bd=0, highlightthickness=0, background="orange")
        frame1.place(x=0, y=0, relwidth=1.0, relheight=.25, anchor="nw")
        frame2.place(x=0, rely=.25, relwidth=1.0, relheight=.75, anchor="nw")
        l1=Label(window,text="Bank Management System",bg='white',fg='black',font=("MS Sans Serif",30,'bold'))
        l1.place(x=500,y=50)
        l2=Label(window,text="Create Account",bg= 'white',fg='black', font=("algerian",40))
        l2.place(x=520,y=140)

        v1=Label(window,text="Account Number", fg='black',bg='orange',font=("times New Roman",18))
        v2=Label(window,text="First Name", fg='black',bg='orange',font=("times New Roman",18))
        v3=Label(window,text="Last Name", fg='black',bg='orange',font=("times New Roman",18))
        v4=Label(window,text="Initial Amount", fg='black',bg='orange',font=("times New Roman",18))
        v5=Label(window,text="Address", fg='black',bg='orange',font=("times New Roman",18))
        v6=Label(window,text="Phone No. ", fg='black',bg='orange',font=("times New Roman",18))
        v7=Label(window,text="Gender", fg='black',bg='orange',font=("times New Roman",18))
        v8=Label(window,text="Email ", fg='black',bg='orange',font=("times New Roman",18))

        v1.place(x=30,y=250)
        v2.place(x=30,y=300)
        v3.place(x=30,y=350)
        v4.place(x=30,y=400)
        v5.place(x=30,y=450)
        v6.place(x=30,y=500)
        v7.place(x=30,y=550)
        v8.place(x=30,y=600)

        acc=StringVar()
        first=StringVar()
        last=StringVar()
        add=StringVar()
        amount=StringVar()
        phone=StringVar()
        email=StringVar()
        e1=Entry(window,textvariable=acc,fg='black',bg='white',width=40,font=("arial",15))
        e1.place(x=230,y=250)
        e2=Entry(window,textvariable=first,fg='black',bg='white',width=40,font=("arial",15))
        e2.place(x=230,y=300)
        e3=Entry(window,textvariable=last,fg='black',bg='white',width=40,font=("arial",15))
        e3.place(x=230,y=350)
        e4=Entry(window,textvariable=amount,fg='black',bg='white',width=40,font=("arial",15))
        e4.place(x=230,y=400)
        e5=Entry(window,textvariable=add,fg='black',bg='white',width=40,font=("arial",15))
        e5.place(x=230,y=450)
        e6=Entry(window,textvariable=phone,fg='black',bg='white',width=40,font=("arial",15))
        e6.place(x=230,y=500)
        e7=IntVar()
        v31=Radiobutton(window,text="Male",fg='black',bg='orange',variable=e7,value=1,font=("Times New Roman",15))
        v31.place(x=230,y=550)
        v32=Radiobutton(window,text="Female",fg='black',bg='orange',variable=e7,value=2,font=("Times New Roman",15))
        v32.place(x=390,y=550)
        e8=Entry(window,textvariable=email,fg='black',bg='white',width=40,font=("arial",15))
        e8.place(x=230,y=600)

        vip=Button(window,text="Submit",width=10,fg='black',font=("Stencil",15), command=lambda:createaccountdb(e1,e2,e3,e4,e5,e6,e7,e8))
        vip.place(x=230,y=750)
        vip1=Button(window,text="Return",width=10,fg='black',font=("Stencil",15), command=main)
        vip1.place(x=500,y=750)
    def checkdetailsdb(e1):
        e1=e1.get()
        if(e1!=''):
            qry="select * from account where account_no={}".format(e1)
            cur.execute(qry)
            get=cur.fetchone()
            cn.commit()
            a1,a2,a3,a4,a5,a6,a7,a8=get


            v2=Label(window,text="First Name", fg='black',bg='orange',font=("times New Roman",18))
            v3=Label(window,text="Last Name", fg='black',bg='orange',font=("times New Roman",18))
            v4=Label(window,text="Account Balance", fg='black',bg='orange',font=("times New Roman",18))
            v5=Label(window,text="Address", fg='black',bg='orange',font=("times New Roman",18))
            v6=Label(window,text="Phone No. ", fg='black',bg='orange',font=("times New Roman",18))
            v7=Label(window,text="Gender", fg='black',bg='orange',font=("times New Roman",18))
            v8=Label(window,text="Email ", fg='black',bg='orange',font=("times New Roman",18))

            vip1=Label(window,text="                        ", fg='black',bg='orange',font=("times New Roman",28))
            vip1.place(x=700,y=244)
            
            v2.place(x=30,y=300)
            v3.place(x=30,y=350)
            v4.place(x=30,y=400)
            v5.place(x=30,y=450)
            v6.place(x=30,y=500)
            v7.place(x=30,y=550)
            v8.place(x=30,y=600)

            first=StringVar()
            first.set(a2)
            last=StringVar()
            last.set(a3)
            add=StringVar()
            add.set(a5)
            amount=StringVar()
            amount.set(a4)
            phone=StringVar()
            phone.set(a6)
            email=StringVar()
            email.set(a8)
            gen=StringVar()
            gen.set(a7)
            e2=Entry(window,textvariable=first,fg='black',bg='white',state='disabled',width=40,font=("arial",15))
            e2.place(x=230,y=300)
            e3=Entry(window,textvariable=last,fg='black',bg='white',state='disabled',width=40,font=("arial",15))
            e3.place(x=230,y=350)
            e4=Entry(window,textvariable=amount,fg='black',bg='white',state='disabled',width=40,font=("arial",15))
            e4.place(x=230,y=400)
            e5=Entry(window,textvariable=add,fg='black',bg='white',state='disabled',width=40,font=("arial",15))
            e5.place(x=230,y=450)
            e6=Entry(window,textvariable=phone,fg='black',bg='white',state='disabled',width=40,font=("arial",15))
            e6.place(x=230,y=500)
            e7=Entry(window,textvariable=gen,fg='black',bg='white',state='disabled',width=40,font=("arial",15))
            e7.place(x=230,y=550)
            e8=Entry(window,textvariable=email,fg='black',bg='white',state='disabled',width=40,font=("arial",15))
            e8.place(x=230,y=600)
        
    def checkdetails():
        frame1 = Frame(bd=0, highlightthickness=0, background="white")
        frame2 =Frame(bd=0, highlightthickness=0, background="orange")
        frame1.place(x=0, y=0, relwidth=1.0, relheight=.25, anchor="nw")
        frame2.place(x=0, rely=.25, relwidth=1.0, relheight=.75, anchor="nw")
        l1=Label(window,text="Bank Management System",bg='white',fg='black',font=("MS Sans Serif",30,'bold'))
        l1.place(x=500,y=50)
        l2=Label(window,text="Check Details",bg= 'white',fg='black', font=("algerian",40))
        l2.place(x=550,y=140)
        v1=Label(window,text="Account Number", fg='black',bg='orange',font=("times New Roman",18))

        v1.place(x=30,y=250)
        

        acc=StringVar()
        e1=Entry(window,textvariable=acc,fg='black',bg='white',width=40,font=("arial",15))
        e1.place(x=230,y=250)

        vip=Button(window,text="Submit",width=10,fg='black',font=("Stencil",15), command=lambda:checkdetailsdb(e1))
        vip.place(x=700,y=244)
        vip1=Button(window,text="Return",width=10,fg='black',font=("Stencil",15), command=main)
        vip1.place(x=500,y=750)
    def withdrawupdate(e1,e2,e3):
        e2=float(e2.get())
        e3=e3.get()
        if(e3!='' and e2>float(e3)):
            e2=e2-float(e3)
            qry="update account set amount={} where account_no={}".format(e2,e1)
            cur.execute(qry)
            cn.commit()

            a1=e2
            v1=Label(window,text="Updated Balance", fg='black',bg='orange',font=("times New Roman",18))
            v1.place(x=30,y=400)
            bal=StringVar()
            bal.set(a1)
            v2=Entry(window,textvariable=bal,fg='black',bg='white',state='disabled',width=40,font=("arial",15))
            v2.place(x=240,y=400)
            new1=Label(window,text='   Withdrawn Successfull       ',bg='orange',fg='indianred2',font=("Berlin sans FB",18))
            new1.place(x=800,y=500)
            vip1=Label(window,text="                        ", fg='black',bg='orange',font=("times New Roman",28))
            vip1.place(x=230,y=750)
        else:
            new1=Label(window,text='   Insufficient amount       ',bg='orange',fg='indianred2',font=("Berlin sans FB",18))
            new1.place(x=800,y=500)
                
    def withdrawdb(e1):
        e1=e1.get()
        if(e1!=''):
            qry="select amount from account where account_no={}".format(e1)
            cur.execute(qry)
            get=cur.fetchone()
            cn.commit()
            a1=get


            v2=Label(window,text="Current Balance", fg='black',bg='orange',font=("times New Roman",18))
            v3=Label(window,text="Withdrawl Amount", fg='black',bg='orange',font=("times New Roman",18))

            v2.place(x=30,y=300)
            v3.place(x=30,y=350)

            bal=StringVar()
            bal.set(a1)
            amount=StringVar()
            
            e2=Entry(window,textvariable=bal,fg='black',bg='white',state='disabled',width=40,font=("arial",15))
            e2.place(x=240,y=300)
            e3=Entry(window,textvariable=amount,fg='black',bg='white',width=40,font=("arial",15))
            e3.place(x=240,y=350)
            vip=Button(window,text="Withdraw",width=10,fg='black',font=("Stencil",15), command=lambda:withdrawupdate(e1,e2,e3))
            vip.place(x=230,y=750)
            vip1=Label(window,text="                        ", fg='black',bg='orange',font=("times New Roman",28))
            vip1.place(x=710,y=244)
    def withdraw():
        frame1 = Frame(bd=0, highlightthickness=0, background="white")
        frame2 =Frame(bd=0, highlightthickness=0, background="orange")
        frame1.place(x=0, y=0, relwidth=1.0, relheight=.25, anchor="nw")
        frame2.place(x=0, rely=.25, relwidth=1.0, relheight=.75, anchor="nw")
        l1=Label(window,text="Bank Management System",bg='white',fg='black',font=("MS Sans Serif",30,'bold'))
        l1.place(x=500,y=50)
        l2=Label(window,text="Balance Withdraw",bg= 'white',fg='black', font=("algerian",40))
        l2.place(x=495,y=140)
        v1=Label(window,text="Account Number", fg='black',bg='orange',font=("times New Roman",18))

        v1.place(x=30,y=250)
        

        acc=StringVar()
        e1=Entry(window,textvariable=acc,fg='black',bg='white',width=40,font=("arial",15))
        e1.place(x=240,y=250)

        vip=Button(window,text="Submit",width=10,fg='black',font=("Stencil",15), command=lambda:withdrawdb(e1))
        vip.place(x=710,y=244)
        vip1=Button(window,text="Return",width=10,fg='black',font=("Stencil",15), command=main)
        vip1.place(x=500,y=750)
    def depositupdate(e1,e2,e3):
        e2=float(e2.get())
        e3=e3.get()
        if(e3!=''):
            e2=e2+float(e3)
            qry="update account set amount={} where account_no={}".format(e2,e1)
            cur.execute(qry)
            cn.commit()

            a1=e2
            v1=Label(window,text="Updated Balance", fg='black',bg='orange',font=("times New Roman",18))
            v1.place(x=30,y=400)
            bal=StringVar()
            bal.set(a1)
            v2=Entry(window,textvariable=bal,fg='black',bg='white',state='disabled',width=40,font=("arial",15))
            v2.place(x=240,y=400)
            new1=Label(window,text='   Amount Deposited Successfully       ',bg='orange',fg='indianred2',font=("Berlin sans FB",18))
            new1.place(x=800,y=500)
            vip1=Label(window,text="                        ", fg='black',bg='orange',font=("times New Roman",28))
            vip1.place(x=230,y=750)
        else:
            new1=Label(window,text='            Insufficient amount            ',bg='orange',fg='indianred2',font=("Berlin sans FB",18))
            new1.place(x=800,y=500)
    def depositdb(e1):
        e1=e1.get()
        if(e1!=''):
            qry="select amount from account where account_no={}".format(e1)
            cur.execute(qry)
            get=cur.fetchone()
            cn.commit()
            a1=get


            v2=Label(window,text="Current Balance", fg='black',bg='orange',font=("Times New Roman",18))
            v3=Label(window,text="Deposit Amount", fg='black',bg='orange',font=("Times New Roman",18))

            v2.place(x=30,y=300)
            v3.place(x=30,y=350)

            bal=StringVar()
            bal.set(a1)
            amount=StringVar()
            
            e2=Entry(window,textvariable=bal,fg='black',bg='white',state='disabled',width=40,font=("arial",15))
            e2.place(x=240,y=300)
            e3=Entry(window,textvariable=amount,fg='black',bg='white',width=40,font=("arial",15))
            e3.place(x=240,y=350)
            vip=Button(window,text="Deposit",width=10,fg='black',font=("Stencil",15), command=lambda:depositupdate(e1,e2,e3))
            vip.place(x=230,y=750)
            vip1=Label(window,text="                        ", fg='black',bg='orange',font=("times New Roman",28))
            vip1.place(x=710,y=244)
    def deposit():
        frame1 = Frame(bd=0, highlightthickness=0, background="white")
        frame2 =Frame(bd=0, highlightthickness=0, background="orange")
        frame1.place(x=0, y=0, relwidth=1.0, relheight=.25, anchor="nw")
        frame2.place(x=0, rely=.25, relwidth=1.0, relheight=.75, anchor="nw")
        l1=Label(window,text="Bank Management System",bg='white',fg='black',font=("MS Sans Serif",30,'bold'))
        l1.place(x=500,y=50)
        l2=Label(window,text="Deposit Amount",bg= 'white',fg='black', font=("algerian",40))
        l2.place(x=495,y=140)
        v1=Label(window,text="Account Number", fg='black',bg='orange',font=("times New Roman",18))

        v1.place(x=30,y=250)
        

        acc=StringVar()
        e1=Entry(window,textvariable=acc,fg='black',bg='white',width=40,font=("arial",15))
        e1.place(x=240,y=250)

        vip=Button(window,text="Submit",width=10,fg='black',font=("Stencil",15), command=lambda:depositdb(e1))
        vip.place(x=710,y=244)
        vip1=Button(window,text="Return",width=10,fg='black',font=("Stencil",15), command=main)
        vip1.place(x=500,y=750)
    def updatedshow(e7):
        frame1 = Frame(bd=0, highlightthickness=0, background="white")
        frame2 =Frame(bd=0, highlightthickness=0, background="orange")
        frame1.place(x=0, y=0, relwidth=1.0, relheight=.25, anchor="nw")
        frame2.place(x=0, rely=.25, relwidth=1.0, relheight=.75, anchor="nw")
        l1=Label(window,text="Bank Management System",bg='white',fg='black',font=("MS Sans Serif",30,'bold'))
        l1.place(x=500,y=50)
        l2=Label(window,text="Update Details",bg= 'white',fg='black', font=("algerian",40))
        l2.place(x=550,y=140)
        v1=Label(window,text="Account Number", fg='black',bg='orange',font=("times New Roman",18))

        v1.place(x=30,y=250)
        

        acc=StringVar()
        acc.set(e7)
        e1=Entry(window,textvariable=acc,fg='black',bg='white',state='disabled',width=40,font=("arial",15))
        e1.place(x=230,y=250)
        vip1=Button(window,text="Return",width=10,fg='black',font=("Stencil",15), command=main)
        vip1.place(x=500,y=750)

        qry="select * from account where account_no={}".format(e7)
        cur.execute(qry)
        get=cur.fetchone()
        cn.commit()
        a1,a2,a3,a4,a5,a6,a7,a8=get


        v2=Label(window,text="First Name", fg='black',bg='orange',font=("times New Roman",18))
        v3=Label(window,text="Last Name", fg='black',bg='orange',font=("times New Roman",18))
        v5=Label(window,text="Address", fg='black',bg='orange',font=("times New Roman",18))
        v6=Label(window,text="Phone No. ", fg='black',bg='orange',font=("times New Roman",18))
        v7=Label(window,text="Gender", fg='black',bg='orange',font=("times New Roman",18))
        v8=Label(window,text="Email ", fg='black',bg='orange',font=("times New Roman",18))

        vip1=Label(window,text="                        ", fg='black',bg='orange',font=("times New Roman",28))
        vip1.place(x=700,y=244)
            
        v2.place(x=30,y=300)
        v3.place(x=30,y=350)
        v5.place(x=30,y=400)
        v6.place(x=30,y=450)
        v7.place(x=30,y=500)
        v8.place(x=30,y=550)

        first=StringVar()
        first.set(a2)
        last=StringVar()
        last.set(a3)
        add=StringVar()
        add.set(a5)
        phone=StringVar()
        phone.set(a6)
        email=StringVar()
        email.set(a8)
        gen=StringVar()
        gen.set(a7)
        e2=Entry(window,textvariable=first,fg='black',bg='white',state='disabled',width=40,font=("arial",15))
        e2.place(x=230,y=300)
        e3=Entry(window,textvariable=last,fg='black',bg='white',state='disabled',width=40,font=("arial",15))
        e3.place(x=230,y=350)
        e5=Entry(window,textvariable=add,fg='black',bg='white',state='disabled',width=40,font=("arial",15))
        e5.place(x=230,y=400)
        e6=Entry(window,textvariable=phone,fg='black',bg='white',state='disabled',width=40,font=("arial",15))
        e6.place(x=230,y=450)
        e7=Entry(window,textvariable=gen,fg='black',bg='white',state='disabled',width=40,font=("arial",15))
        e7.place(x=230,y=500)
        e8=Entry(window,textvariable=email,fg='black',bg='white',state='disabled',width=40,font=("arial",15))
        e8.place(x=230,y=550)
    def updatedetails(e1,e2,e3,e4,e5,e6,e7):
        e1=e1.get()
        e2=e2.get()
        e3=e3.get()
        e4=e4.get()
        e5=e5.get()
        e6=e6.get()
        if e1!='' and e2!='' and e3!='' and e4!='' and e5!='' and e6!='':
            qry="update account set first='{}',last='{}',address='{}',phone='{}',gender='{}',email='{}' where account_no={}".format(e1,e2,e3,e4,e5,e6,e7)
            cur.execute(qry)
            cn.commit()
            
            new1=Label(window,text='   Account Updated       ',bg='orange',fg='indianred2',font=("Berlin sans FB",18))
            new1.place(x=800,y=500)
            vip1=Label(window,text="                        ", fg='black',bg='orange',font=("times New Roman",28))
            vip1.place(x=230,y=750)
            updatedshow(e7)
        else:
            new1=Label(window,text='   Wrong Details       ',bg='orange',fg='indianred2',font=("Berlin sans FB",18))
            new1.place(x=800,y=750)
    def updateaccountdb(e1):
        e1=e1.get()
        if(e1!=''):
            qry="select * from account where account_no={}".format(e1)
            cur.execute(qry)
            get=cur.fetchone()
            cn.commit()
            a1,a2,a3,a4,a5,a6,a7,a8=get


            v2=Label(window,text="First Name", fg='black',bg='orange',font=("times New Roman",18))
            v3=Label(window,text="Last Name", fg='black',bg='orange',font=("times New Roman",18))
            v5=Label(window,text="Address", fg='black',bg='orange',font=("times New Roman",18))
            v6=Label(window,text="Phone No. ", fg='black',bg='orange',font=("times New Roman",18))
            v7=Label(window,text="Gender", fg='black',bg='orange',font=("times New Roman",18))
            v8=Label(window,text="Email ", fg='black',bg='orange',font=("times New Roman",18))

            vip1=Label(window,text="                        ", fg='black',bg='orange',font=("times New Roman",28))
            vip1.place(x=700,y=244)
            
            v2.place(x=30,y=300)
            v3.place(x=30,y=350)
            v5.place(x=30,y=400)
            v6.place(x=30,y=450)
            v7.place(x=30,y=500)
            v8.place(x=30,y=550)

            first=StringVar()
            first.set(a2)
            last=StringVar()
            last.set(a3)
            add=StringVar()
            add.set(a5)
            phone=StringVar()
            phone.set(a6)
            email=StringVar()
            email.set(a8)
            gen=StringVar()
            gen.set(a7)
            e2=Entry(window,textvariable=first,fg='black',bg='white',state='disabled',width=40,font=("arial",15))
            e2.place(x=230,y=300)
            e3=Entry(window,textvariable=last,fg='black',bg='white',state='disabled',width=40,font=("arial",15))
            e3.place(x=230,y=350)
            e5=Entry(window,textvariable=add,fg='black',bg='white',state='disabled',width=40,font=("arial",15))
            e5.place(x=230,y=400)
            e6=Entry(window,textvariable=phone,fg='black',bg='white',state='disabled',width=40,font=("arial",15))
            e6.place(x=230,y=450)
            e7=Entry(window,textvariable=gen,fg='black',bg='white',state='disabled',width=40,font=("arial",15))
            e7.place(x=230,y=500)
            e8=Entry(window,textvariable=email,fg='black',bg='white',state='disabled',width=40,font=("arial",15))
            e8.place(x=230,y=550)



            v2=Label(window,text="First Name", fg='black',bg='orange',font=("times New Roman",18))
            v3=Label(window,text="Last Name", fg='black',bg='orange',font=("times New Roman",18))
            v5=Label(window,text="Address", fg='black',bg='orange',font=("times New Roman",18))
            v6=Label(window,text="Phone No. ", fg='black',bg='orange',font=("times New Roman",18))
            v7=Label(window,text="Gender", fg='black',bg='orange',font=("times New Roman",18))
            v8=Label(window,text="Email ", fg='black',bg='orange',font=("times New Roman",18))

            
            v2.place(x=750,y=300)
            v3.place(x=750,y=350)
            v5.place(x=750,y=400)
            v6.place(x=750,y=450)
            v7.place(x=750,y=500)
            v8.place(x=750,y=550)

            first=StringVar()
            first.set(a2)
            last=StringVar()
            last.set(a3)
            add=StringVar()
            add.set(a5)
            phone=StringVar()
            phone.set(a6)
            email=StringVar()
            email.set(a8)
            gen=StringVar()
            gen.set(a7)
            e2=Entry(window,textvariable=first,fg='black',bg='white',width=40,font=("arial",15))
            e2.place(x=880,y=300)
            e3=Entry(window,textvariable=last,fg='black',bg='white',width=40,font=("arial",15))
            e3.place(x=880,y=350)
            e5=Entry(window,textvariable=add,fg='black',bg='white',width=40,font=("arial",15))
            e5.place(x=880,y=400)
            e6=Entry(window,textvariable=phone,fg='black',bg='white',width=40,font=("arial",15))
            e6.place(x=880,y=450)
            e7=Entry(window,textvariable=gen,fg='black',bg='white',width=40,font=("arial",15))
            e7.place(x=880,y=500)
            e8=Entry(window,textvariable=email,fg='black',bg='white',width=40,font=("arial",15))
            e8.place(x=880,y=550)

            vip2=Button(window,text="Update",width=10,fg='black',font=("Stencil",15), command=lambda:updatedetails(e2,e3,e5,e6,e7,e8,e1))
            vip2.place(x=1130,y=750)
    def updateaccount():
        frame1 = Frame(bd=0, highlightthickness=0, background="white")
        frame2 =Frame(bd=0, highlightthickness=0, background="orange")
        frame1.place(x=0, y=0, relwidth=1.0, relheight=.25, anchor="nw")
        frame2.place(x=0, rely=.25, relwidth=1.0, relheight=.75, anchor="nw")
        l1=Label(window,text="Bank Management System",bg='white',fg='black',font=("MS Sans Serif",30,'bold'))
        l1.place(x=500,y=50)
        l2=Label(window,text="Update Details",bg= 'white',fg='black', font=("algerian",40))
        l2.place(x=550,y=140)
        v1=Label(window,text="Account Number", fg='black',bg='orange',font=("times New Roman",18))

        v1.place(x=30,y=250)
        

        acc=StringVar()
        e1=Entry(window,textvariable=acc,fg='black',bg='white',width=40,font=("arial",15))
        e1.place(x=230,y=250)

        vip=Button(window,text="Submit",width=10,fg='black',font=("Stencil",15), command=lambda:updateaccountdb(e1))
        vip.place(x=700,y=244)
        vip1=Button(window,text="Return",width=10,fg='black',font=("Stencil",15), command=main)
        vip1.place(x=500,y=750)
    def deleteaccountdb(e1):
        e1=e1.get()
        if(e1!=''):
            qry="delete from account where account_no={}".format(e1)
            cur.execute(qry)
            get=cur.fetchone()
            cn.commit()
            new1=Label(window,text='   Account Deleted       ',bg='orange',fg='indianred2',font=("Berlin sans FB",20))
            new1.place(x=500,y=400)
            vip1=Label(window,text="                        ", fg='black',bg='orange',font=("times New Roman",28))
            vip1.place(x=700,y=244)
            
    def deleteaccount():
        frame1 = Frame(bd=0, highlightthickness=0, background="white")
        frame2 =Frame(bd=0, highlightthickness=0, background="orange")
        frame1.place(x=0, y=0, relwidth=1.0, relheight=.25, anchor="nw")
        frame2.place(x=0, rely=.25, relwidth=1.0, relheight=.75, anchor="nw")
        l1=Label(window,text="Bank Management System",bg='white',fg='black',font=("MS Sans Serif",30,'bold'))
        l1.place(x=500,y=50)
        l2=Label(window,text="Delete Account",bg= 'white',fg='black', font=("algerian",40))
        l2.place(x=550,y=140)
        v1=Label(window,text="Account Number", fg='black',bg='orange',font=("times New Roman",18))

        v1.place(x=30,y=250)
        

        acc=StringVar()
        e1=Entry(window,textvariable=acc,fg='black',bg='white',width=40,font=("arial",15))
        e1.place(x=230,y=250)

        vip=Button(window,text="Submit",width=10,fg='black',font=("Stencil",15), command=lambda:deleteaccountdb(e1))
        vip.place(x=700,y=244)
        vip1=Button(window,text="Return",width=10,fg='black',font=("Stencil",15), command=main)
        vip1.place(x=500,y=750)
    def main():
        frame1 = Frame(bd=0, highlightthickness=0, background="white")
        frame2 =Frame(bd=0, highlightthickness=0, background="orange")
        frame1.place(x=0, y=0, relwidth=1.0, relheight=.15, anchor="nw")
        frame2.place(x=0, rely=.15, relwidth=1.0, relheight=.85, anchor="nw")
        l1=Label(window,text="Bank Management System",bg='white',fg='black',font=("MS Sans Serif",30,'bold'))
        l1.place(x=500,y=50)
        b1=Button(window,text="Creat Account",fg='Black',width=20,font=("Stencil",14),command=createaccount)
        b1.place(x=140,y=200)
        b2=Button(window,text="Balance Withdraw",fg='Black',width=20,font=("Stencil",14),command=withdraw)
        b2.place(x=140,y=350)
        b3=Button(window,text="Update Account",fg='Black',width=20,font=("Stencil",14),command=updateaccount)
        b3.place(x=140,y=500)
        b4=Button(window,text="Logout",fg='Black',width=8,font=("Stencil",8),command=window1)
        b4.place(x=1420,y=100)
        b5=Button(window,text="Check Account Details",fg='Black',width=20,font=("Stencil",14),command=checkdetails)
        b5.place(x=1140,y=200)
        b6=Button(window,text="Deposit Amount",fg='Black',width=20,font=("Stencil",14),command=deposit)
        b6.place(x=1140,y=350)
        b7=Button(window,text="Delete Account",fg='Black',width=20,font=("Stencil",14),command=deleteaccount)
        b7.place(x=1140,y=500)
    def login_database(e1,e2):
        e1=e1.get()
        e2=e2.get()
        a=e1,e2
        cur.execute('select * from login')
        get=cur.fetchall()
        for i in get:
            if a==i:
                main()
                break
            else:
                new1=Label(window,text='Username or password is incorrect',bg='orange',fg='indianred2',font=("Berlin sans FB",18))
                new1.place(x=400,y=680)
    def login():
        frame1 = Frame(bd=0, highlightthickness=0, background="white")
        frame2 =Frame(bd=0, highlightthickness=0, background="orange")
        frame1.place(x=0, y=0, relwidth=1.0, relheight=.25, anchor="nw")
        frame2.place(x=0, rely=.25, relwidth=1.0, relheight=.75, anchor="nw")
        l1=Label(window,text="Bank Management System",bg='white',fg='black',font=("MS Sans Serif",30,'bold'))
        l1.place(x=500,y=50)
        l2=Label(window,text="Login",bg= 'white',fg='black', font=("algerian",50))
        l2.place(x=620,y=120)
        l3=Label(window,text="Enter Userid",bg='orange',font=("Times New Roman",18))
        l3.place(x=500,y=250)
        l4=Label(window,text="Enter Password",bg='orange',font=("Times New Roman",18))
        l4.place(x=500,y=450)
        email_text=StringVar()
        e1=Entry(window,bg= 'white',font=("arial",18),textvariable=email_text)
        e1.place(x=500,y=285)
        password_text=StringVar()
        e2=Entry(window,bg='white',font=("arial",18),textvariable=password_text,show='*')
        e2.place(x=500,y=485)
        b1=Button(window,text="Login",fg='Black',width=10,font=("Stencil",15),command=lambda:login_database(e1,e2))
        b1.place(x=480,y=590)
        b2=Button(window,text="return",fg='Black',width=10,font=("Stencil",15),command=window1)
        b2.place(x=750,y=590)
    def signup_database(e1,e2,e3,e4,e5):
        e1=e1.get()
        e2=e2.get()
        e3=e3.get()
        e4=e4.get()
        e5=e5.get()
        try:
            if e1!='' and e2!=0 and e3!=0 and e4!='' and e5!='':
                
                if int(e3)==1:
                    gen='M'
                if int(e3)==2:
                    gen='F'
             
                cur.execute("CREATE TABLE IF NOT EXISTS user(name varchar(20) NOT NULL,age Int(2) NOT NULL,gender char(3) NOT NULL,username varchar(20) primary key,password varchar(20) NOT NULL)")
                qry="INSERT INTO user values('{}',{},'{}','{}','{}')".format(e1,e2,gen,e4,e5)
                cur.execute(qry)
                cn.commit()
                cur.execute("CREATE TABLE IF NOT EXISTS login(user_id varchar(20),password varchar(20))")
                qry="INSERT INTO login values('{}','{}')".format(e4,e5)
                cur.execute(qry)
                cn.commit()
                new2=Label(window,text='Signup \n Successfully           ',bg='orange',fg='indianred2',font=("Berlin sans FB",18))
                new2.place(x=800,y=500)
                vip=Button(window,text="Login",width=10,fg='black',font=("Stencil",15), command=login)
                vip.place(x=230,y=750)
            else:
                new1=Label(window,text='Please fill      \n all the fields',bg='orange',fg='indianred2',font=("Berlin sans FB",18))
                new1.place(x=800,y=500)
        except:
            new1=Label(window,text='Username already \n exist       ',bg='orange',fg='indianred2',font=("Berlin sans FB",18))
            new1.place(x=800,y=500)
            
    def signup():#signup page
        frame1 = Frame(bd=0, highlightthickness=0, background="white")
        frame2 =Frame(bd=0, highlightthickness=0, background="orange")
        frame1.place(x=0, y=0, relwidth=1.0, relheight=.25, anchor="nw")
        frame2.place(x=0, rely=.25, relwidth=1.0, relheight=.75, anchor="nw")
        l1=Label(window,text="Bank Management System",bg='white',fg='black',font=("MS Sans Serif",30))
        l1.place(x=500,y=50)
        l2=Label(window,text="Sign Up",bg= 'white',fg='black', font=("algerian",50))
        l2.place(x=620,y=120)
    
        v1=Label(window,text="Name ", fg='black',bg='orange',font=("times New Roman",18))
        v2=Label(window,text="Age", fg='black',bg='orange',font=("Times New Roman",18))
        v3=Label(window,text="Gender", fg='black',bg='orange',font=("Times New Roman",18))
        v4=Label(window,text="Username", fg='black',bg='orange',font=("Times New Roman",18))
        v5=Label(window,text="Password", fg='black',bg='orange',font=("Times New Roman",18))

        v1.place(x=30,y=250)
        v2.place(x=30,y=350)
        v3.place(x=30,y=450)
        v4.place(x=30,y=550)
        v5.place(x=30,y=650)
        name_text=StringVar()
        e1=Entry(window,textvariable=name_text,fg='black',bg='white',font=("arial",15))
        e1.place(x=230,y=250)
        age_text=IntVar()
        e2=Entry(window,textvariable=age_text,fg='black',bg='white',font=("arial",15))
        e2.place(x=230,y=350)
        e3=IntVar()
        v31=Radiobutton(window,text="Male",fg='black',bg='orange',variable=e3,value=1,font=("Times New Roman",18))
        v31.place(x=230,y=450)
        v32=Radiobutton(window,text="Female",fg='black',bg='orange',variable=e3,value=2,font=("Times New Roman",18))
        v32.place(x=390,y=450)
        vip=Button(window,text="Submit",width=10,fg='black',font=("Stencil",15), command=lambda:signup_database(e1,e2,e3,e4,e5))
        vip.place(x=230,y=750)
        vip1=Button(window,text="Return",width=10,fg='black',font=("Stencil",15), command=window1)
        vip1.place(x=500,y=750)
        email_text=StringVar()
        e4=Entry(window,bg= 'white',font=("arial",15),textvariable=email_text)
        e4.place(x=230,y=550)
        password_text=StringVar()
        e5=Entry(window,bg='white',font=("arial",15),textvariable=password_text,show='*')
        e5.place(x=230,y=650)

        
    b1=Button(window,text="Login",width=20,font=("Stencil",18),command=login)
    b1.place(x=550,y=400)
    b2=Button(window,text="Signup",width=20,font=("Stencil",18), command=signup)
    b2.place(x=550,y=550)
    window.mainloop()
window1()
